phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - aws s3 cp s3://taskmaster-resources/application-deploy.yml ./src/main/resources
  build:
    commands:
      - mvn clean package -Dspring.profiles.active=test
  post_build:
    commands:
      - mv target/*.jar ./taskmaster.jar

artifacts:
  files:
    - taskmaster.jar